import { useMemo, useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'
import { PALETTE } from '@/art/palette'
import { toonGradient } from '@/art/toon'
import { clamp, fbm, smoothstep } from '@/core/math'
import type { Terrain } from '@/world/terrain'
import type { LevelDef } from '@/levels/types'

/**
 * Sky, ground and water.
 *
 * The ground mesh is generated by sampling the same `terrain.height(x, z)` the
 * simulation walks on, so the two can never disagree — an animal is never
 * hovering or sunk, because there is only one surface and both halves of the
 * game ask it the same question.
 */

/**
 * Ground resolution. Two hundred and twenty segments looked no better than a
 * hundred and eighty and cost thirty thousand triangles, which on integrated
 * graphics is worth more than the detail.
 */
const GROUND_SEGMENTS = 180

/* ------------------------------------------------------------------- sky */

const SKY_VERT = /* glsl */ `
  varying vec3 vDir;
  void main() {
    vDir = normalize(position);
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`

/**
 * Burnt orange, banded rather than smooth. The bands are deliberate: this is a
 * world printed on newsprint in 1977, and a perfectly smooth gradient would be
 * the one thing in the frame that looked expensive.
 */
const SKY_FRAG = /* glsl */ `
  uniform vec3 high;
  uniform vec3 low;
  uniform float flash;
  uniform float time;
  varying vec3 vDir;
  void main() {
    float t = clamp(vDir.y * 0.5 + 0.5, 0.0, 1.0);

    /* Heat shimmer. Rather than distorting the frame in a post pass — which
       costs a full-screen draw for an effect nobody would look at twice — the
       band of sky right on the horizon ripples, which is where you would
       actually see it over hot ground. */
    float horizon = 1.0 - smoothstep(0.0, 0.09, abs(vDir.y));
    float ripple = sin(vDir.x * 42.0 + time * 2.1) * sin(vDir.z * 37.0 - time * 1.7);
    t += ripple * 0.012 * horizon;

    float banded = floor(t * 7.0) / 7.0;
    t = mix(t, banded, 0.55);
    vec3 c = mix(low, high, t);
    // A little of the ground's heat bleeding up into the first band of sky.
    c += horizon * 0.05 * (0.5 + ripple * 0.5);
    c += flash * 0.65;
    gl_FragColor = vec4(c, 1.0);
  }
`

export function Sky({ level, flash }: { level: LevelDef; flash: React.RefObject<number> }) {
  const mat = useMemo(
    () =>
      new THREE.ShaderMaterial({
        uniforms: {
          high: { value: new THREE.Color(level.mood.sky) },
          low: { value: new THREE.Color(PALETTE.skyLow) },
          flash: { value: 0 },
          time: { value: 0 },
        },
        vertexShader: SKY_VERT,
        fragmentShader: SKY_FRAG,
        side: THREE.BackSide,
        depthWrite: false,
        fog: false,
      }),
    [level.mood.sky],
  )

  useFrame((state) => {
    mat.uniforms.flash!.value = flash.current ?? 0
    mat.uniforms.time!.value = state.clock.elapsedTime
  })

  return (
    <mesh material={mat} renderOrder={-1000} frustumCulled={false}>
      <sphereGeometry args={[900, 20, 12]} />
    </mesh>
  )
}

/* ------------------------------------------------------------- lighting */

export function Lighting({ level }: { level: LevelDef }) {
  const { scene } = useThree()
  useMemo(() => {
    scene.fog = new THREE.FogExp2(new THREE.Color(level.mood.fog), level.mood.fogDensity)
    scene.background = null
  }, [scene, level])

  return (
    <>
      {/* A single low sun, so the toon bands fall across the landscape rather
          than lighting everything evenly from overhead. */}
      <directionalLight position={[120, 160, 90]} intensity={2.4} color={PALETTE.sun} />
      {/* Fill is teal, not grey: "deep teal shadows". */}
      <ambientLight intensity={1.0} color={PALETTE.shadowSoft} />
      <hemisphereLight args={[level.mood.sky, PALETTE.shadow, 0.6]} />
    </>
  )
}

/* ---------------------------------------------------------------- ground */

export function Ground({ terrain, level }: { terrain: Terrain; level: LevelDef }) {
  const geometry = useMemo(() => buildGroundGeometry(terrain, level), [terrain, level])
  const material = useMemo(
    () =>
      new THREE.MeshToonMaterial({
        vertexColors: true,
        gradientMap: toonGradient(),
      }),
    [],
  )

  /* A flat apron well beyond the playable bounds. The heightfield mesh has to
     stop somewhere, and without this the world visibly ends in a straight edge
     with sky underneath it. */
  const skirt = useMemo(() => {
    const b = terrain.def.bounds
    const cx = (b.minX + b.maxX) / 2
    const cz = (b.minZ + b.maxZ) / 2
    const g = new THREE.PlaneGeometry(2600, 2600)
    g.rotateX(-Math.PI / 2)
    g.translate(cx, terrain.height(cx, cz) - 2.5, cz)
    return g
  }, [terrain])
  const skirtMat = useMemo(
    () => new THREE.MeshBasicMaterial({ color: new THREE.Color(level.mood.ground) }),
    [level.mood.ground],
  )

  return (
    <>
      <mesh geometry={skirt} material={skirtMat} renderOrder={-5} />
      <mesh geometry={geometry} material={material} receiveShadow />
    </>
  )
}

function buildGroundGeometry(terrain: Terrain, level: LevelDef): THREE.BufferGeometry {
  const b = terrain.def.bounds
  const w = b.maxX - b.minX
  const d = b.maxZ - b.minZ
  const geo = new THREE.PlaneGeometry(w, d, GROUND_SEGMENTS, GROUND_SEGMENTS)
  geo.rotateX(-Math.PI / 2)
  geo.translate((b.minX + b.maxX) / 2, 0, (b.minZ + b.maxZ) / 2)

  const pos = geo.attributes.position as THREE.BufferAttribute
  const colours = new Float32Array(pos.count * 3)
  const base = new THREE.Color(level.mood.ground)
  const light = new THREE.Color(PALETTE.groundLight)
  const dark = new THREE.Color(PALETTE.groundDark)
  const rock = new THREE.Color(PALETTE.rockDark)
  const wet = new THREE.Color(PALETTE.water)
  const tarC = new THREE.Color(PALETTE.tar)
  const c = new THREE.Color()

  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i)
    const z = pos.getZ(i)
    const h = terrain.height(x, z)
    pos.setY(i, h)

    /* Colour by slope and by how close to the trail we are. The graded corridor
       is paler and dustier — a visible trail the herd is meant to follow, which
       does more for readability than any minimap arrow. */
    const slope = terrain.slope(x, z)
    const route = terrain.routeInfo(x, z)
    const onTrail = 1 - smoothstep(terrain.def.corridorWidth * 0.35, terrain.def.corridorWidth * 0.9, route.dist)

    c.copy(base)
    /* Mottling, at two scales. Broad patches of paler and darker dirt, plus a
       finer grain on top. Without it the badlands are one flat field of orange
       and the eye has nothing to judge distance or speed against. */
    const broad = fbm(x * 0.011, z * 0.011, 3)
    const fine = fbm(x * 0.09 + 7.7, z * 0.09 - 3.1, 2)
    c.lerp(light, clamp(broad * 0.55 + 0.28, 0, 0.6))
    c.lerp(dark, clamp(-broad * 0.5 + fine * 0.22, 0, 0.5))
    c.lerp(rock, clamp(slope * 2.6, 0, 0.85))
    // The trodden trail: paler, and the only straight-ish thing in the frame.
    c.lerp(light, onTrail * 0.34)
    c.lerp(dark, clamp((-h / 30) * 0.9, 0, 0.7))

    if (terrain.waterDepth(x, z) > 0.05) {
      c.lerp(wet, clamp(terrain.waterDepth(x, z) / 2.5, 0.2, 0.8))
    }
    for (const t of terrain.def.tar) {
      const dist = Math.hypot(x - t.x, z - t.z)
      if (dist < t.radius) c.lerp(tarC, 1 - smoothstep(t.radius * 0.3, t.radius, dist))
    }

    colours[i * 3] = c.r
    colours[i * 3 + 1] = c.g
    colours[i * 3 + 2] = c.b
  }

  geo.setAttribute('color', new THREE.BufferAttribute(colours, 3))
  geo.computeVertexNormals()
  return geo
}

/* ----------------------------------------------------------------- water */

export function Water({ terrain }: { terrain: Terrain }) {
  const refs = useRef<(THREE.Mesh | null)[]>([])

  const bodies = useMemo(
    () =>
      terrain.def.water.map((w) => ({
        ...w,
        level: terrain.waterLevelAt(w.x, w.z) ?? 0,
      })),
    [terrain],
  )

  const material = useMemo(
    () =>
      new THREE.MeshBasicMaterial({
        color: new THREE.Color(PALETTE.water),
        transparent: true,
        opacity: 0.78,
        depthWrite: false,
      }),
    [],
  )

  useFrame((state) => {
    // A slow swell, so standing water does not look like a sheet of plastic.
    for (const m of refs.current) {
      if (m) m.position.y += Math.sin(state.clock.elapsedTime * 0.8) * 0.004
    }
  })

  if (bodies.length === 0) return null

  return (
    <>
      {bodies.map((w, i) => (
        <mesh
          key={i}
          ref={(el) => {
            refs.current[i] = el
          }}
          material={material}
          position={[w.x, w.level, w.z]}
          rotation={[-Math.PI / 2, 0, 0]}
          renderOrder={2}
        >
          <circleGeometry args={[w.radius, 40]} />
        </mesh>
      ))}
    </>
  )
}
